waymo_classes=   {0: 'unknown(sdc)',
 1: 'car',
 2: 'truck',
 3: 'bus',
 4: 'other_large_vehicle',
 5: 'bicycle',
 6: 'motorcycle',
 7: 'trailer',
 8: 'person',
 9: 'cyclist',
 10: 'motorcyclist',
 11: 'bird',
 12: 'ground_animal',
 13: 'construction_cone_pole',
 14: 'pole',
 15: 'other_pedestrian_object',
 16: 'sign',
 17: 'traffic light',
 18: 'building',
 19: 'road',
 20: 'lane_marker',
 21: 'road_marker',
 22: 'sidewalk',
 23: 'vegetation',
 24: 'sky',
 25: 'ground',
 26: 'dynamic',
 27: 'static',
 255: 'ignore_label'}


waymo_things={1: 'car',
 2: 'truck',
 3: 'bus',
 4: 'other_large_vehicle',
 7: 'trailer',
 8: 'person',
 9: 'cyclist',
 10: 'motorcyclist'}



waymo_stuff={0: 'unknown(sdc)',
 5: 'bicycle',
 6: 'motorcycle',
 11: 'bird',
 12: 'ground_animal',
 13: 'construction_cone_pole',
 14: 'pole',
 15: 'other_pedestrian_object',
 16: 'sign',
 17: 'traffic_light',
 18: 'building',
 19: 'road',
 20: 'lane_marker',
 21: 'road_marker',
 22: 'sidewalk',
 23: 'vegetation',
 24: 'sky',
 25: 'ground',
 26: 'dynamic',
 27: 'static',
 255: 'ignore_label'}


